config/routes.rb
Rails.application.routes.draw do

  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end  
  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
    validates :title, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]
  
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blogs_params)
    else
      @blog = Blog.new
    end
  end

 def confirm
   @blog = Blog.new(blogs_params)
   render :new if @blog.invalid?
 end

  def create
    @blog = Blog.new(blogs_params)
    if @blog.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    @blog.update(blogs_params)
    if @blog.save
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end  
  end
  
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end

  private
    def blogs_params
      params.require(:blog).permit(:title, :content)
    end
    
  # idをキーとして値を取得するメソッド
    def set_blog
      @blog = Blog.find(params[:id])
    end  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    if params[:back]
      @contact = Contact.new(contacts_params)
    else
      @contact = Contact.new
    end  
  end

  def confirm
    @contact = Contact.new(contacts_params)
    render :new if @contact.invalid?
  end  

  def create
    @contact=Contact.create(contacts_params)
    if @contact.save
      redirect_to new_contact_path, notice: "お問い合わせありがとうございました！"
    else
      render 'new'
    end  
  end
  
  private
  def contacts_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@blog) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>

  <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= f.submit "登録する" %>
<% end %>

<%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>

<%= render 'form' %>

app/views/blogs/index.html.erb
<p><%= notice %></p>

<h1>ブログ一覧</h1>

<% @blogs.each do |blog| %>
  <p>タイトル:<%= blog.title %></p>
  <p>本文:<%= blog.content %></p>
  <%= link_to "ブログを編集する", edit_blog_path(blog.id) %>
  <%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete , data: { confirm: '本当に削除していいですか？' }%>
<% end %>

<br>

<%= link_to "ブログを作成する", new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

<%= render 'form' %>

app/views/contacts/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@contact) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>

  <!-- @contact.nameと@contact.emailと@contact.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>名前:<%= @contact.name %></p>
  <p>メールアドレス:<%= @contact.email %></p>
  <p>本文:<%= @contact.content %></p>
  <%= f.submit "登録する" %>
<% end %>

<%= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back' %>
<% end %>

app/views/contacts/index.html.erb
<h1>お問い合わせフォーム</h1>

<%= link_to "お問い合わせはこちら", new_contact_path %>

app/views/contacts/new.html.erb
<p><%= notice %></p>

<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
<!--#バリデーションエラーの件数を表示します。-->
      <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
      <ul>
<!--# @contact.errorsは@contactをバリデーションした際のエラー情報です。-->
<!--# full_messagesは複数のエラーメッセージを表します。-->
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "お問い合わせにもどる", contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achieve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>